# Generated by Django 4.0.3 on 2022-03-22 20:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Main_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('price_before', models.IntegerField(default=0)),
                ('brand', models.CharField(default='', max_length=30)),
                ('description', models.TextField(blank=True, default='', help_text='HTML', max_length=5000, null=True)),
                ('image', models.ImageField(upload_to='uploads/products/')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='petstore.main_category')),
            ],
        ),
        migrations.CreateModel(
            name='Kedi_Kap',
            fields=[
                ('products_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='petstore.products')),
                ('seramik_or_plastik', models.CharField(choices=[('1', 'seramik'), ('0', 'plastik')], max_length=1)),
            ],
            bases=('petstore.products',),
        ),
        migrations.CreateModel(
            name='Kedi_Kum',
            fields=[
                ('products_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='petstore.products')),
                ('silika_or_bentonit', models.CharField(choices=[('1', 'silika'), ('0', 'bentonit')], max_length=1)),
                ('topaklanan_or_emici', models.CharField(choices=[('1', 'topaklanan'), ('0', 'emici')], max_length=1)),
                ('litre', models.CharField(default='', max_length=10)),
            ],
            bases=('petstore.products',),
        ),
        migrations.CreateModel(
            name='Kedi_Mama',
            fields=[
                ('products_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='petstore.products')),
                ('kuru_or_yas', models.CharField(choices=[('1', 'kuru'), ('0', 'yas')], max_length=1)),
                ('yavru_or_yetiskin', models.CharField(choices=[('1', 'yavru'), ('0', 'yetiskin')], max_length=1)),
                ('kisir_or_not', models.CharField(choices=[('1', 'kisir'), ('0', 'not')], max_length=1)),
                ('neyli', models.CharField(default='', max_length=50)),
            ],
            bases=('petstore.products',),
        ),
        migrations.CreateModel(
            name='Kedi_Odul',
            fields=[
                ('products_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='petstore.products')),
                ('biskuvi_or_stick', models.CharField(choices=[('1', 'biskuvi'), ('0', 'stick')], max_length=1)),
                ('yavru_or_yetiskin', models.CharField(choices=[('1', 'yavru'), ('0', 'yetiskin')], max_length=1)),
                ('neyli', models.CharField(default='', max_length=50)),
            ],
            bases=('petstore.products',),
        ),
        migrations.CreateModel(
            name='Kedi_Oyuncak',
            fields=[
                ('products_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='petstore.products')),
                ('oltali_or_pelus', models.CharField(choices=[('3', 'tunel'), ('2', 'lazer'), ('1', 'oltali'), ('0', 'pelus')], max_length=1)),
            ],
            bases=('petstore.products',),
        ),
        migrations.CreateModel(
            name='Kedi_Tirmalama',
            fields=[
                ('products_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='petstore.products')),
            ],
            bases=('petstore.products',),
        ),
        migrations.CreateModel(
            name='Kopek_Kap',
            fields=[
                ('products_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='petstore.products')),
                ('tur', models.CharField(choices=[('2', 'seramik'), ('1', 'metal'), ('0', 'plastik')], max_length=1)),
            ],
            bases=('petstore.products',),
        ),
        migrations.CreateModel(
            name='Kopek_Mama',
            fields=[
                ('products_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='petstore.products')),
                ('kuru_or_yas', models.CharField(choices=[('1', 'kuru'), ('0', 'yas')], max_length=1)),
                ('yavru_or_yetiskin', models.CharField(choices=[('1', 'yavru'), ('0', 'yetiskin')], max_length=1)),
                ('kisir_or_not', models.CharField(choices=[('1', 'kisir'), ('0', 'not')], max_length=1)),
                ('neyli', models.CharField(default='', max_length=50)),
            ],
            bases=('petstore.products',),
        ),
        migrations.CreateModel(
            name='Kopek_Odul',
            fields=[
                ('products_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='petstore.products')),
                ('kemik_or_stick_or_biskuvi', models.CharField(choices=[('2', 'kemik'), ('1', 'stick'), ('0', 'biskuvi')], max_length=1)),
                ('yavru_or_yetiskin', models.CharField(choices=[('1', 'yavru'), ('0', 'yetiskin')], max_length=1)),
                ('neyli', models.CharField(default='', max_length=50)),
            ],
            bases=('petstore.products',),
        ),
        migrations.CreateModel(
            name='Kopek_Oyuncak',
            fields=[
                ('products_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='petstore.products')),
                ('tur', models.CharField(choices=[('2', 'dis ipi'), ('1', 'cigneme'), ('0', 'pelus')], max_length=1)),
            ],
            bases=('petstore.products',),
        ),
        migrations.CreateModel(
            name='Kopek_Tasma',
            fields=[
                ('products_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='petstore.products')),
                ('gogus_or_boyun', models.CharField(choices=[('1', 'gogus'), ('0', 'boyun')], max_length=1)),
                ('beden', models.CharField(choices=[('1', 'small'), ('1', 'medium'), ('0', 'large')], max_length=1)),
                ('deri_or_zincir', models.CharField(choices=[('1', 'kisir'), ('0', 'not')], max_length=1)),
            ],
            bases=('petstore.products',),
        ),
        migrations.CreateModel(
            name='Kopek_Yatak',
            fields=[
                ('products_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='petstore.products')),
                ('beden', models.CharField(choices=[('3', 'small'), ('2', 'medium'), ('1', 'large'), ('0', 'xlarge')], max_length=1)),
            ],
            bases=('petstore.products',),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField()),
                ('address', models.CharField(blank=True, default='', max_length=50)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('status', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petstore.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petstore.products')),
            ],
        ),
    ]
