# Generated by Django 4.0.3 on 2022-03-25 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petstore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kedi_kum',
            old_name='litre',
            new_name='neyli',
        ),
    ]
