# Generated by Django 4.0.3 on 2022-03-25 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petstore', '0003_kedi_tirmalama_karton_or_ahsap'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kopek_tasma',
            old_name='beden',
            new_name='neyli',
        ),
    ]
