# Generated by Django 4.0.3 on 2022-03-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petstore', '0004_rename_beden_kopek_tasma_neyli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kopek_tasma',
            name='deri_or_zincir',
            field=models.CharField(choices=[('1', 'deri'), ('0', 'zincir')], max_length=1),
        ),
        migrations.AlterField(
            model_name='kopek_tasma',
            name='neyli',
            field=models.CharField(choices=[('2', 'small'), ('1', 'medium'), ('0', 'large')], max_length=1),
        ),
    ]
