# Generated by Django 4.0.3 on 2022-03-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petstore', '0005_alter_kopek_tasma_deri_or_zincir_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kopek_tasma',
            name='deri_or_zincir',
            field=models.CharField(choices=[('2', 'kumas'), ('1', 'deri'), ('0', 'zincir')], max_length=1),
        ),
        migrations.AlterField(
            model_name='kopek_tasma',
            name='neyli',
            field=models.CharField(default='', max_length=50),
        ),
    ]
