# Generated by Django 4.0.3 on 2022-03-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petstore', '0006_alter_kopek_tasma_deri_or_zincir_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(to='petstore.products'),
        ),
    ]
