# Generated by Django 4.0.3 on 2022-03-29 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petstore', '0007_remove_order_product_order_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('header', models.CharField(default='', max_length=70)),
                ('image_large', models.ImageField(upload_to='uploads/campaigns/')),
                ('image_square', models.ImageField(upload_to='uploads/campaigns/')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='HTML', max_length=5000, null=True)),
                ('campaign_type', models.CharField(choices=[('hepsi', 'hepsi'), ('kedi', 'kedi'), ('köpek', 'köpek')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='district',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='neighborhood',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.CreateModel(
            name='OrderGuest',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='petstore.order')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
            bases=('petstore.order',),
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petstore.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petstore.products')),
            ],
        ),
        migrations.CreateModel(
            name='OrderCustomer',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='petstore.order')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petstore.customer')),
            ],
            bases=('petstore.order',),
        ),
    ]
