# Generated by Django 4.0.3 on 2022-03-29 23:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petstore', '0008_campaign_remove_order_customer_remove_order_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='bitti',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='orderguest',
            name='phone',
            field=models.CharField(default='', max_length=50),
        ),
    ]
