# Generated by Django 4.0.3 on 2022-03-30 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petstore', '0009_rename_status_order_bitti_alter_order_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='solo_price',
            field=models.FloatField(default=0),
        ),
    ]
