# Generated by Django 4.0.3 on 2022-03-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petstore', '0010_orderproduct_solo_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bitti',
            field=models.CharField(choices=[('Hazırlanıyor', 'Hazırlanıyor'), ('Kargoda', 'Kargoda'), ('Tamamlandı', 'Tamamlandı')], default='Hazırlanıyor', max_length=20),
        ),
    ]
