# Generated by Django 4.0.3 on 2022-04-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petstore', '0015_alter_subscription_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, default='', max_length=3000),
        ),
    ]
