# Generated by Django 4.0.3 on 2022-04-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petstore', '0017_campaign_updated_at_campaign_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='campaign_type',
            field=models.CharField(choices=[('genel', 'genel'), ('kedi', 'kedi'), ('köpek', 'köpek')], max_length=20),
        ),
    ]
