# Generated by Django 4.0.3 on 2022-04-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petstore', '0018_alter_campaign_campaign_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='image_large',
            new_name='image_880x285',
        ),
        migrations.AddField(
            model_name='campaign',
            name='image_885x450',
            field=models.ImageField(default='', upload_to='uploads/campaigns/'),
            preserve_default=False,
        ),
    ]
