# Generated by Django 4.0.3 on 2022-04-08 18:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petstore', '0019_rename_image_large_campaign_image_880x285_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_no',
            field=models.IntegerField(default=10000, unique=True, validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MinValueValidator(10000)]),
        ),
    ]
